name: graphql_server
version: 1.0.0-beta.2
author: Tobe O <thosakwe@gmail.com>
description: Base package for implementing GraphQL servers. You might prefer `package:angel_graphql`, the fastest way to implement GraphQL backends in Dart.
homepage: https://github.com/angel-dart/graphql
environment:
  sdk: ">=1.8.0 <3.0.0"
dependencies:
  angel_serialize: ^2.0.0
  collection: ^1.0.0
  graphql_schema: ^1.0.0
  graphql_parser: ^1.0.0
  meta: ^1.0.0
  recase: ^2.0.0
  tuple: ^1.0.0
dev_dependencies:
  test: ">=0.12.0 <2.0.0"