name: angel_framework
version: 2.0.0-alpha.12
description: A high-powered HTTP server with dependency injection, routing and much more.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_framework
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_container: ^1.0.0-alpha
  angel_http_exception: ^1.0.0
  angel_model: ^1.0.0
  angel_route: ^3.0.0
  body_parser: ^1.0.0
  charcode: ^1.0.0
  combinator: ^1.0.0
  file: ^5.0.0
  http_parser: ^3.0.0
  http2: ">=0.1.7 <2.0.0"
  logging: ">=0.11.3 <1.0.0"
  matcher: ^0.12.0
  merge_map: ^1.0.0
  meta: ^1.0.0
  mime: ^0.9.3
  mock_request: ^1.0.0
  path: ^1.0.0
  stack_trace: ^1.0.0
  tuple: ^1.0.0
  uuid: ^1.0.0
dev_dependencies:
  http: ^0.11.3
  io: ^0.3.0
  test: ^1.0.0