name: angel
description: An easily-extensible web server framework in Dart.
version: 1.0.0-dev
author: thosakwe <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel
publish_to: none
dependencies:
  angel_auth: ^1.0.0-dev
  angel_configuration: ^1.0.0-dev
  angel_diagnostics: ^1.0.0-dev
  angel_framework: ^1.0.0-dev
  angel_mongo: ^1.0.0-dev
  angel_mustache: ^1.0.0-dev
  angel_static: ^1.0.0
  furlong:
    path: /Users/tobe/Source/Dart/furlong
  json_god: ^2.0.0-beta
  validate: ^1.5.2
dev_dependencies:
  http: ^0.11.3
  grinder: ^0.8.0+2
  test: ^0.12.13
transformers:
- angel_configuration
