# Default server configuration.
host: 127.0.0.1
mongo_db: mongodb://localhost:27017/angel
db:
  migrate:
    database: angel
    username: root
    password: password
  web:
    database: angel
    username: username
    password: password